name:                hedgehog-checkers-lens
version:             0.1.0.0
homepage: https://github.com/bitemyapp/hedgehog-checkers#readme
license:             BSD3
author:              Chris Allen
maintainer:          cma@bitemyapp.com
copyright:           2017, Chris Allen
category:            Web
description:         hedgehog-checkers-lens provides the various lens, prism, setter, and traversal laws as ready-to-use properties.
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - hedgehog >= 0.5 && < 0.6
  - hedgehog-checkers
  - lens >= 4 && < 5

library:
  source-dirs: src
  dependencies:
  exposed-modules:
    - Hedgehog.Checkers.Lens.Properties

tests:
  tests:
    main: tests.hs
    source-dirs: tests
    dependencies:
      - hedgehog-checkers-lens
    ghc-options:
      - -threaded
      - -Wall
      - -rtsopts
      - -with-rtsopts=-N
